# Generated by Django 5.1.3 on 2024-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedRequests',
            fields=[
                ('accreqid', models.AutoField(db_column='AccReqID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Accepted_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adminusers',
            fields=[
                ('adminid', models.AutoField(db_column='AdminID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('login', models.CharField(db_column='Login', max_length=15)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'AdminUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationid', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saveduserpath',
            fields=[
                ('pathid', models.AutoField(db_column='PathID', primary_key=True, serialize=False)),
                ('startpoint', models.CharField(db_column='StartPoint', max_length=255)),
                ('endpoint', models.CharField(db_column='EndPoint', max_length=255)),
                ('pathname', models.CharField(db_column='PathName', max_length=255)),
                ('notify', models.CharField(db_column='Notify', max_length=255)),
            ],
            options={
                'db_table': 'SavedUserPath',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supportchatlogging',
            fields=[
                ('messageid', models.AutoField(db_column='MessageID', primary_key=True, serialize=False)),
                ('messagetext', models.CharField(db_column='MessageText', max_length=255)),
                ('messagedatetime', models.DateTimeField(db_column='MessageDateTime')),
            ],
            options={
                'db_table': 'SupportChatLogging',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrequests',
            fields=[
                ('requestid', models.AutoField(db_column='RequestID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('whatheppens', models.CharField(db_column='WhatHeppens', max_length=255)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('imageaddress', models.CharField(blank=True, db_column='ImageAddress', max_length=255, null=True)),
                ('geolocation', models.CharField(db_column='Geolocation', max_length=255)),
            ],
            options={
                'db_table': 'UserRequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('login', models.CharField(db_column='Login', max_length=15)),
                ('passwd', models.CharField(db_column='Passwd', max_length=20)),
                ('points', models.BigIntegerField(db_column='Points')),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
